export const GOOGLE_PLAY_ACHIEVEMENT_IDS = {
  first_saga: 'CgkIwr6kn8QLEAIQBQ',
  skald_slayer: 'CgkIwr6kn8QLEAIQDg',
  vikingr_victor: 'CgkIwr6kn8QLEAIQCQ',
  jarl_breaker: 'CgkIwr6kn8QLEAIQAw',
  berserkr_bane: 'CgkIwr6kn8QLEAIQAQ',
  bloodied_victor: 'CgkIwr6kn8QLEAIQDA',
  untouched_fate: 'CgkIwr6kn8QLEAIQDw',
  thunder_caller: 'CgkIwr6kn8QLEAIQBw',
  apple_keeper: 'CgkIwr6kn8QLEAIQCw',
  tricksters_mark: 'CgkIwr6kn8QLEAIQCA',
  norns_claim: 'CgkIwr6kn8QLEAIQDQ',
  favor_thief: 'CgkIwr6kn8QLEAIQBA',
  shield_wall: 'CgkIwr6kn8QLEAIQBg',
  divine_timing: 'CgkIwr6kn8QLEAIQCg',
  saga_veteran: 'CgkIwr6kn8QLEAIQAg',
  dice_monoculture: 'CgkIwr6kn8QLEAIQGQ',
  oops_all_axes: 'CgkIwr6kn8QLEAIQEg',
  pointy_weather: 'CgkIwr6kn8QLEAIQFQ',
  helmet_convention: 'CgkIwr6kn8QLEAIQFw',
  shield_sandwich: 'CgkIwr6kn8QLEAIQEQ',
  sticky_fingers: 'CgkIwr6kn8QLEAIQEw',
  gods_on_do_not_disturb: 'CgkIwr6kn8QLEAIQEA',
  face_tank: 'CgkIwr6kn8QLEAIQGA',
  queue_conqueror: 'CgkIwr6kn8QLEAIQFA',
  dragon_sits_on_gold: 'CgkIwr6kn8QLEAIQFg',
} as const;

export type AchievementKey = keyof typeof GOOGLE_PLAY_ACHIEVEMENT_IDS;
